-- 137: shift_schedule → THREE-shift operating model (supersedes mig 130's
-- day/night/rotating/flexible). Our real operation runs three shifts plus a
-- rotating pattern:
--   delelott (délelőttös) | delutan (délutános) | ejszaka (éjszakás) | valtott (váltott)
-- "flexible" is removed. English-slug storage, Hungarian UI labels, hu/en bulk
-- import normalizer — unchanged conventions, new value set.
--
-- Consolidation rule change (see consolidationEngine.service.js): SAME SHIFT ONLY.
-- Every cross-shift pairing is incompatible; an EMPTY shift is incompatible with
-- everyone (never auto-placed — flagged for data entry).
--
-- Prod row counts verified BEFORE this migration (2026-07-13): all 288 employees
-- had shift_schedule = NULL; ZERO rows used day/night/rotating/flexible. So the
-- data remap below is a no-op on prod — it exists only for dev/fresh DBs that may
-- hold legacy values.

BEGIN;

-- 1) Drop the old CHECK constraint (name is auto-generated by mig 130's inline
--    CHECK; drop by discovery so this is portable across DBs).
DO $$
DECLARE c text;
BEGIN
  SELECT conname INTO c
    FROM pg_constraint
   WHERE conrelid = 'employees'::regclass
     AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%shift_schedule%';
  IF c IS NOT NULL THEN
    EXECUTE format('ALTER TABLE employees DROP CONSTRAINT %I', c);
  END IF;
END $$;

-- 2) Map any existing legacy data to the new model (no-op on prod: 0 legacy rows).
--    night → ejszaka; rotating → valtott. "day" and "flexible" have no clean
--    three-shift target → NULL (flagged for re-entry rather than mis-assigned).
UPDATE employees SET shift_schedule = 'ejszaka' WHERE shift_schedule = 'night';
UPDATE employees SET shift_schedule = 'valtott' WHERE shift_schedule = 'rotating';
UPDATE employees SET shift_schedule = NULL     WHERE shift_schedule IN ('day', 'flexible');

-- 3) New CHECK constraint — the three shifts + rotating.
ALTER TABLE employees
  ADD CONSTRAINT employees_shift_schedule_check
  CHECK (shift_schedule IN ('delelott', 'delutan', 'ejszaka', 'valtott'));

COMMENT ON COLUMN employees.shift_schedule IS
  'Shift pattern: delelott | delutan | ejszaka | valtott. Consolidation-engine input — SAME SHIFT ONLY may share a room; an empty shift is never auto-placed (flagged for data entry).';

-- 4) Re-align the consolidation shift-compatibility matrix to SAME-SHIFT-ONLY
--    (identity), IF the consolidation_config table exists (it does on
--    sandbox/dev where mig 132 ran; it does NOT on prod, which never applied 132).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'consolidation_config') THEN
    UPDATE consolidation_config SET shift_compatibility = '{
      "delelott": {"delelott": true,  "delutan": false, "ejszaka": false, "valtott": false},
      "delutan":  {"delelott": false, "delutan": true,  "ejszaka": false, "valtott": false},
      "ejszaka":  {"delelott": false, "delutan": false, "ejszaka": true,  "valtott": false},
      "valtott":  {"delelott": false, "delutan": false, "ejszaka": false, "valtott": true}
    }'::jsonb;
  END IF;
END $$;

COMMIT;
